CREATE TABLE IF NOT EXISTS games (
    id TEXT PRIMARY KEY,
    name_ko TEXT NOT NULL,
    name_en TEXT,
    short_description TEXT NOT NULL,
    rules_summary TEXT NOT NULL,
    min_players INTEGER NOT NULL CHECK (min_players > 0),
    max_players INTEGER NOT NULL CHECK (max_players >= min_players),
    avg_play_time_minutes INTEGER NOT NULL CHECK (avg_play_time_minutes > 0),
    difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
    genre TEXT NOT NULL CHECK (genre IN ('strategy', 'party', 'puzzle', 'family', 'cooperative')),
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_beginner_friendly INTEGER NOT NULL DEFAULT 0,
    is_kid_friendly INTEGER NOT NULL DEFAULT 0,
    is_party_game INTEGER NOT NULL DEFAULT 0,
    is_strategy_game INTEGER NOT NULL DEFAULT 0,
    play_style TEXT NOT NULL DEFAULT 'competitive',
    image_url TEXT,
    image_source TEXT,
    image_license TEXT,
    image_alt TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS game_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    alias TEXT NOT NULL,
    normalized_alias TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS game_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    target_game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    relation_type TEXT NOT NULL,
    CHECK (source_game_id <> target_game_id),
    UNIQUE (source_game_id, target_game_id, relation_type)
);

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    provider TEXT,
    display_name TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS anonymous_sessions (
    id TEXT PRIMARY KEY,
    device_label TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS user_events (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    session_id TEXT,
    event_type TEXT NOT NULL,
    game_id TEXT REFERENCES games(id) ON DELETE SET NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS played_games (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    played_at TIMESTAMPTZ NOT NULL,
    rating INTEGER CHECK (rating BETWEEN 1 AND 5),
    notes TEXT
);

CREATE TABLE IF NOT EXISTS hidden_games (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, game_id)
);

CREATE TABLE IF NOT EXISTS recognition_jobs (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    session_id TEXT,
    status TEXT NOT NULL,
    image_original_stored INTEGER NOT NULL DEFAULT 0,
    hint_text TEXT,
    top_game_id TEXT REFERENCES games(id) ON DELETE SET NULL,
    confidence DOUBLE PRECISION,
    needs_retake INTEGER NOT NULL DEFAULT 0,
    message TEXT NOT NULL,
    confirmed_game_id TEXT REFERENCES games(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS recognition_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recognition_id TEXT NOT NULL REFERENCES recognition_jobs(id) ON DELETE CASCADE,
    game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    confidence DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS recommendation_logs (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    session_id TEXT,
    request_payload JSONB NOT NULL,
    response_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    token_hint TEXT NOT NULL,
    role TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_imports (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    status TEXT NOT NULL,
    preview_payload JSONB NOT NULL,
    summary JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    applied_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS admin_audit_events (
    id TEXT PRIMARY KEY,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    summary JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_game_aliases_normalized ON game_aliases(normalized_alias);
CREATE INDEX IF NOT EXISTS idx_game_relations_source ON game_relations(source_game_id, relation_type);
CREATE INDEX IF NOT EXISTS idx_games_filter ON games(min_players, max_players, avg_play_time_minutes, difficulty, genre);
CREATE INDEX IF NOT EXISTS idx_user_events_recent ON user_events(user_id, session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_recognition_jobs_recent ON recognition_jobs(user_id, session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_recommendation_logs_recent ON recommendation_logs(user_id, session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_audit_recent ON admin_audit_events(created_at DESC);
